server:
  port: 9090
spring:
  profiles:
    active: dev
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: Customer-Microservice
            client-secret: oxH22jW1RDYR1TtAvwPBAY8WJD39us9e
            authorization-grant-type: authorization_code
            scope:
              - openid
        provider:
          keycloak:
            issuer-uri: http://localhost:8090/realms/Entity-Creation-Work-Flow
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8090/realms/Entity-Creation-Work-Flow
  datasource:
    url: jdbc:postgresql://localhost:5432/customer
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: update

    properties:
      hibernate:
        dialect:
          org.hibernate.dialect.PostgreSQLDialect
springdoc:
  swagger-ui:
    oauth:
      client-id: Customer-Microservice
      client-secret: oxH22jW1RDYR1TtAvwPBAY8WJD39us9e

